### ISSUE TITLE
Migrate Opentracing to Open Telemetry

### ISSUE THREAD

**Issue by Sgitario** [snowdrop/spring-boot-istio-distributed-tracing-booster#48]
Plus, update the documentation accordingly.

**Comment by cmoulliard** [comment]
Dont forget to track please and to deliver !

**Comment by Sgitario** [comment]
I tried to use the Spring Cloud Sleuth OpenTelemetry plugin and it worked pretty well but for Spring Boot 2.7.
The problem is that our Snowdrop BOM has not been bumped yet to 2.7, so we depend on https://github.com/snowdrop/spring-boot-bom/issues/205.
