### ISSUE TITLE
Add integration tests to cover this example

### ISSUE THREAD

**Issue by Sgitario** [snowdrop/spring-boot-istio-distributed-tracing-booster#49]
At the moment, this example is lacking any kind of test. We should cover the functionality and ensure the correct configuration with Istio. 
The tests should be executed in pull requests.

**Comment by cmoulliard** [comment]
Don't forget to track this ticket ? Discuss your idea with Libor and team to get from them what we think we should do ? @Sgitario

**Comment by Sgitario** [comment]
My idea was to run the tests as part of the CI PR pipeline, nothing to do with the QE tests.

**Comment by cmoulliard** [comment]
> CI PR pipeline, nothing to do with the QE tests.

ok.

**Comment by Sgitario** [comment]
It seems we can't easily use any of the two available clusters (ocp 3.11 or Kind) that supports Istio: https://issues.redhat.com/browse/OSSMDOC-105
Closing with won't do.
