### ISSUE TITLE
OpenshiftIT.tracingTest:70 HTTP status 403

### ISSUE THREAD

**Issue by liborfuka** [snowdrop/spring-boot-istio-distributed-tracing-booster#72]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 16.559 s <<< FAILURE! - in me.snowdrop.istio.dt.OpenshiftIT
[ERROR] tracingTest  Time elapsed: 16.189 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 

expected: 200
 but was: 403
        at me.snowdrop.istio.dt.OpenshiftIT.tracingTest(OpenshiftIT.java:70)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   OpenshiftIT.tracingTest:70 
expected: 200
 but was: 403

https://github.com/snowdrop/istio-distributed-tracing-example/blob/a0b5ddbde27ffa02c698d1a486b45eb7d94df265/tests/src/test/java/me/snowdrop/istio/dt/OpenshiftIT.java#L70

**Comment by jacobdotcosta** [comment]
Fixed by #75
