### ISSUE TITLE
Why do we continue to use our deprecated GAV

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/spring-boot-istio-distributed-tracing-booster#8]
Why do we continue to use our deprecated GAV instead of the opentracing spring web starter ?

This GAV - https://goo.gl/sGpwj1

```
<groupId>me.snowdrop</groupId>
<artifactId>opentracing-tracer-jaeger-spring-web-starter</artifactId>
<version>${opentracing-tracer.version}</version>
```

should be 

https://github.com/opentracing-contrib/java-spring-web/blob/release-0.3.2/opentracing-spring-web/pom.xml#L5-L10

```
<groupId>io.opentracing.contrib</groupId>
<artifactId>opentracing-spring-web</artifactId>
<version>0.3.2-SNAPSHOT</version>
```

**REMARK** : The opentracing spring web starter should be part of our next Spring Boot BOM !

**Comment by geoand** [comment]
The autoconfiguration module is not in the project you mention, but in

https://github.com/opentracing-contrib/java-spring-cloud.

Last time I checked there wasn't a release that contained the
autoconfiguration code we added, but I will have to check again.

**Comment by geoand** [comment]
Yes, the java-spring-cloud module is the one that is necessary.
The code is at:
https://github.com/opentracing-contrib/java-spring-cloud/tree/master/opentracing-spring-cloud-starter-jaeger

**Comment by geoand** [comment]
I updated the booster to use the latest release of `opentracing-contrib/java-spring-cloud` which now contains the migrated autoconfiguration code.

**Comment by geoand** [comment]
Tested it with both FMP and s2i
